apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod2
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  containers:
    - name: container
      image: kubetm/app
      ports:
        - containerPort: 8080