apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-object
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stateless-app1
  metrics:
    - type: Object
      object:
        metric:
          name: requests-per-second
        target:
          type: Value
          value: 10
        describedObject:
          apiVersion: networking.k8s.io/v1beta1
          kind: Ingress
          name: ingress-hpa