apiVersion: v1
kind: Pod
metadata:
  name: pod1-with-no-execute2
spec:
  tolerations:
    - effect: NoExecute
      key: out-of-disk
      operator: Exists
  containers:
    - name: container
      image: kubetm/app
  terminationGracePeriodSeconds: 0